### PR TITLE
Added support for Enumeration's :)

### PR DESCRIPTION
**Pull request by PureKrome**
- Can now parse an appsetting key/value to an enumeration.
- Updated the Map (extension method) to be case insensitive (using Ordinal.IgnoreCase).
- Updated dotSettings file for nicer formatting.

Also, this requires #4 to be merged, first (as this is a branch off #4 branch).

### CODE REVIEW

**Comment by luisrudge** [comment]
thanks! ❤️

**Comment by luisrudge** [comment]
published here: https://www.nuget.org/packages/Configurator/3.1.0

**Comment by PureKrome** [comment]
Woot! thank you thank you thank you!

**Comment by luisrudge** [comment]
no no. thank you :D

**Pull request merged**
